### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: Qwen/Qwen3-VL-4B-Thinking
adapter_name_or_path: saves/qwen3vl-4b-visual_cot_4k-visual_cot_gqa_2k-sft-lorar256-ep10/checkpoint-2000
template: qwen2_vl
trust_remote_code: true

### export
export_dir: output/qwen3vl_lora_sft
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
